name: over_the_bike_fit
description: Cycling app with neon design and charts.
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.66.0
  health: ^13.2.1
  permission_handler: ^11.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/icon/heart.png
    - assets/icon/bike_ui_dark.png
